on:
  push:
    branches:
      - master

name: Docker Build and Push

jobs:
  publish_docker_image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}:latest \
          --tag ghcr.io/$GITHUB_ACTOR/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}:$(echo $GITHUB_SHA | head -c7) \
          .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}:latest
          docker push ghcr.io/$GITHUB_ACTOR/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}:$(echo $GITHUB_SHA | head -c7)
